name: Build and Deploy jaeihyun publishing Platform

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Debug - Check file structure
        run: |
          echo "=== Root directory ==="
          ls -la
          echo "=== Books directory ==="
          ls -la books/ || echo "books directory not found"
          echo "=== Blog directory ==="
          ls -la blog/ || echo "blog directory not found"

      - name: Render Quarto Project
        run: |
          echo "Starting Quarto render..."
          quarto render
          echo "Quarto render completed"
          
      - name: Debug - Check output directory
        run: |
          echo "=== Checking docs directory ==="
          ls -la docs/ || echo "docs directory not found"

      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4